export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce solution with product catalog, shopping cart, and secure checkout process.",
    tags: ["React", "Node.js", "MongoDB", "Stripe"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
  {
    id: 2,
    title: "Real-time Chat Application",
    description: "Collaborative chat app with real-time messaging, user authentication, and message history.",
    tags: ["React", "Express", "WebSocket", "PostgreSQL"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
  {
    id: 3,
    title: "Task Management Dashboard",
    description: "Interactive dashboard for managing tasks with drag-and-drop functionality and team collaboration.",
    tags: ["React", "TypeScript", "Firebase", "Tailwind CSS"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
  {
    id: 4,
    title: "Weather App",
    description: "Real-time weather application with location-based forecasts and detailed weather analytics.",
    tags: ["React", "API Integration", "Geolocation"],
    github: "https://github.com",
    demo: "https://example.com",
  },
  {
    id: 5,
    title: "Blog Platform",
    description: "Markdown-based blog platform with user authentication, comments, and SEO optimization.",
    tags: ["Next.js", "PostgreSQL", "Prisma", "Markdown"],
    github: "https://github.com",
    demo: "https://example.com",
  },
  {
    id: 6,
    title: "Portfolio Website",
    description: "Modern, responsive portfolio website showcasing projects and professional background.",
    tags: ["Next.js", "React", "Tailwind CSS"],
    github: "https://github.com",
    demo: "https://example.com",
  },
];
