export const projects = [
  {
    id: 1,
    title: "ParkWise Mobile Application",
    description: "A mobile application that helps users find parking spots and provides real-time information about parking availability.",
    image: "/projects/parkwise.png",
    tags: ["React Native", "Node.js", "Express", "PostgreSQL"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
  {
    id: 2,
    title: "BiteHub Mobile Application",
    description: "A mobile application that helps users order food from different restaurants and provides real-time information about food availability.",
    image: "/projects/bitehub.png",
    tags: ["React Native", "Express", "Node.js", "PostgreSQL"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
  {
    id: 3,
    title: "Akwa-Flo: Water Management System",
    description: "A mobile application that helps users order water, monitor their water consumption and provides real-time information about water availability.",
    image: "/projects/akwaflo.png",
    tags: ["React", "Node.js", "PostgreSQL"],
    github: "https://github.com",
    demo: "https://example.com",
    featured: true,
  },
];
