export const skillsData = {
  frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "HTML/CSS",
    "JavaScript",
    "Framer Motion",
    "Redux",
  ],
  backend: [
    "Node.js",
    "Express",
    "Python",
    "REST APIs",
    "GraphQL",
    "Authentication",
    "WebSocket",
  ],
  database: [
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Firebase",
    "Prisma ORM",
    "Sequelize",
  ],
  tools: [
    "Git & GitHub",
    "Docker",
    "AWS",
    "Vercel",
    "VS Code",
    "Postman",
    "Figma",
    "Linux",
  ],
};
